### ISSUE TITLE
First option when switching to "contains any" is messed up

### ISSUE THREAD

**Issue by mattgow** [fatfreecrm/ransack_ui#1]
![Advanced Search UI bug](https://f.cloud.github.com/assets/142467/37638/d17d16c8-548a-11e2-935a-46415436cc9a.PNG)

Steps to reproduce: 
- Do a search for "contains any" (or "is any" or "blah any") and specify a few options
-  Now toggle the search operator to something that doesn't accept multiple options
- Now toggle back to an "any" operator

Result
- The first option you specified will show as an empty box

Expected Result
- It should be formatted correctly

**Comment by ndbroadbent** [comment]
I think I've fixed this during #2, so please try it again after Steve deploys the new version

**Comment by steveyken** [comment]
This looks good

**Comment by steveyken** [comment]
was broken again but fixed with d32b3fff4dd8aa84509131154688b8f51fa48f76
