### ISSUE TITLE
Pre-filling a search using query string is broken in specific case

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/ransack_ui#3]
Steps to reproduce:
- Create a search using url query string (ransack supports this)
- Include a filter with the "is" predicate
- When clicking on the subsequent url to load the page (using get request and query params) the search form doesn't prepopulate the "Is" query part correctly. See screengrab (the select box AND the text box are visible)

![stage](https://f.cloud.github.com/assets/149198/49537/131c6b18-596a-11e2-8709-4bccecbb22ab.png)

**Comment by steveyken** [comment]
Another way to reproduce this:
- Goto Opportunities tab, select advanced search
- Search for opportunity "Stage", contains any, add two statues.
- Change "Stage" to "Assigned to"

**Comment by markedmondson** [comment]
The above should come pretty close, can you try and comment?

**Comment by steveyken** [comment]
Thanks, gets us closer to the solution... need to work out how to handle key value pairs but that's a bigger question...

**Comment by ndbroadbent** [comment]
I think this should be fixed in the next release
