### ISSUE TITLE
Update ransack_ui to support lambda in inclusion matchers

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/ransack_ui#4]
Ransack UI reads the validates :inclusion => ... on models to come up with options for the dropdown boxes. This currently doesn't support cases where :in => lambda { ... }. See http://api.rubyonrails.org/classes/ActiveModel/Validations/HelperMethods.html#method-i-validates_inclusion_of

**Comment by markedmondson** [comment]
It already does this!

https://github.com/ndbroadbent/ransack_ui/blob/master/lib/ransack_ui/ransack_overrides/helpers/form_builder.rb#L110

**Comment by steveyken** [comment]
It works for arrays but not for lambdas

**Comment by ndbroadbent** [comment]
Oh! I was totally wrong. If the lambda just returns an array, then yeah, we can definitely support this. For some reason, I thought you were talking about where the validation itself happened inside a lambda.

**Comment by steveyken** [comment]
Yeah that's right. I'd love to replace (in `models/entities/opportunity.rb`)

`validates :stage, :inclusion => { :in => Setting.unroll(:opportunity_stage).map{|s| s.last.to_s } }`

with 

`validates :stage, :inclusion => { :in => -> { Setting.unroll(:opportunity_stage).map{|s| s.last.to_s } } }`

At the moment, Setting is getting initialized a little too early during start up and we had a few issues before. E.g. if db hasn't been migrated yet and therefore settings table doesn't exist.

**Comment by steveyken** [comment]
c7a03d3 resolves this
